# Generated by Django 6.0 on 2026-02-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên tài liệu')),
                ('file', models.FileField(upload_to='pdfs/', verbose_name='File đính kèm')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
