# Generated by Django 6.0 on 2026-03-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_orientation', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_path', models.CharField(max_length=500)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
